<?php include "interfaz/administrador/layouts/parte_superior.php"?>

<?php include "interfaz/administrador/layouts/header.php"?>

<?php include "interfaz/administrador/layouts/footer.php"?>

<?php if(empty($_POST['mes'])){ $_POST['mes']=date('Y-m-d 00:00'); }
$consulta = mysqli_query($lfmc['sql'], "SELECT * FROM reservaciones WHERE salida BETWEEN '".date('Y-').$_POST['mes']."-00 00:00' AND '".date('Y-').$_POST['mes']."-31 23:00' ORDER BY id DESC");
while ($dato = mysqli_fetch_assoc($consulta)){
    $reservaciones[] = $dato;
}
?>

<!--Inicio del contenido principal-->
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800"><i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i> Reportes</h1>
        </div>
        <form class="row" action="reportes" method="POST">
            <div class="form-group col-4">
                <select class="form-control" name="mes">
                    <option value="01" <?php echo ($_POST['mes']=='01')?'selected':'';?>>Enero</option>
                    <option value="02" <?php echo ($_POST['mes']=='02')?'selected':'';?>>Febrero</option>
                    <option value="03" <?php echo ($_POST['mes']=='03')?'selected':'';?>>Marzo</option>
                    <option value="04" <?php echo ($_POST['mes']=='04')?'selected':'';?>>Abril</option>
                    <option value="05" <?php echo ($_POST['mes']=='05')?'selected':'';?>>Mayo</option>
                    <option value="06" <?php echo ($_POST['mes']=='06')?'selected':'';?>>Junio</option>
                    <option value="07" <?php echo ($_POST['mes']=='07')?'selected':'';?>>Julio</option>
                    <option value="08" <?php echo ($_POST['mes']=='08')?'selected':'';?>>Agosto</option>
                    <option value="09" <?php echo ($_POST['mes']=='09')?'selected':'';?>>Septiembre</option>
                    <option value="10" <?php echo ($_POST['mes']=='10')?'selected':'';?>>Octubre</option>
                    <option value="11" <?php echo ($_POST['mes']=='11')?'selected':'';?>>Noviembre</option>
                    <option value="12" <?php echo ($_POST['mes']=='12')?'selected':'';?>>Diciembre</option>
                </select>
            </div>
            <div class="col-4">
                <button type="submit" class="btn btn-success" style="position:absolute; left:0; top: 0px;">Reporte por mes</button>
            </div>
        </form>
</div>
<hr class="sidebar-divider">

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <?php $total = 0; if(count($reservaciones)>0){?>
            <div class="table-responsive">
                <table id="tablareservaciones" class="table table-striped table-bordered table-condensed" style="width:100%">
                <thead class="text-center">
                    <tr>
                        <th>ID</th>
                        <th>Cliente</th>
                        <th>Teléfono</th>
                        <th>Número de habitación</th>
                        <th>Precio</th>
                        <th>Entrada</th>
                        <th>Salida</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($reservaciones as $reservacion){
                        $f1   = new DateTime($reservacion['entrada']);
                        $f2   = new DateTime($reservacion['salida']);
                        $diff = $f1->diff($f2);
                        $cliente = Obtener($reservacion['cliente_id'],'usuarios');
                        $habitacion = Obtener($reservacion['habitacion_id'],'habitaciones');?>
                        <tr>
                            <td><?php echo $reservacion['id'];?></td>
                            <td><?php echo $cliente['nombre'];?></td>
                            <td><?php echo $cliente['telefono'];?></td>
                            <td>
                                <input type="hidden" id="hbt_<?php echo $reservacion['id'];?>" value="<?php echo $reservacion['habitacion_id'];?>">
                                <?php echo $habitacion['nro'];?>
                            </td>
                            <td><?php echo $habitacion['precio'];?></td>
                            <td><?php echo $reservacion['entrada'];?></td>
                            <td><?php echo $reservacion['salida'];?></td>
                            <td><?php echo $habitacion['precio']*$diff->days;?>$</td>
                        </tr>
                    <?php $total += $habitacion['precio']*$diff->days; }?>
                </tbody>                   
                </table>                    
            </div>
            <?php  echo "<h4 class='text-right'>Total: $total$</h4>"; }else{ echo '<h4 class="text-center">Sin resultados</h4>'; }?>
        </div>
    </div>  
</div>
<!--Final del contenido principal-->

<?php include "interfaz/administrador/layouts/parte_inferior.php"?>