
<?php include "interfaz/administrador/layouts/parte_superior.php"?>
<?php include "interfaz/administrador/layouts/footer.php"?>


<!--Inicio del contenido principal-->
<div class="container-fluid">
     <!-- Page Heading -->
     <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"><i class="fa fa-user fa-fw"></i> Usuarios</h1>
        <div class="row">
     	
     		<div class="col-lg-12">
     			<button id="btnNuevo" type="button" class="btn btn-success" data-toggle="modal">Nuevo usuario</button>
     		</div>
     	</div>               
     </div>
</div>

<hr class="sidebar-divider">

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">        
                <table id="tablausuarios" class="table table-striped table-bordered table-condensed" style="width:100%">
                <thead class="text-center">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Usuario</th>
                        <th>Correo</th>
                        <th>Teléfono</th>
                        <th>Rol del usuario</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $usuarios = ObtenerTodos('usuarios');
                    foreach($usuarios as $usuario){?>
                    <tr>
                        <td><?php echo $usuario['id'];?></td>
                        <td><?php echo $usuario['nombre'];?></td>
                        <td><?php echo $usuario['usuario'];?></td>
                        <td><?php echo $usuario['correo'];?></td>
                        <td><?php echo $usuario['telefono'];?></td>
                        <td><?php echo $usuario['tipo'];?></td>
                        <td></td>
                    </tr>
                    <?php }?>
                </tbody>                   
                </table>                    
            </div>
        </div>
    </div>  
</div>
<script>
    $(document).ready(function(){
        tablausuarios = $("#tablausuarios").DataTable({
            "columnDefs":[{
            "targets": -1,
            "data":null,
            "defaultContent": "<div class='text-center'><div class='btn-group'><button class='btn btn-primary btnEditar'>Editar</button><button class='btn btn-danger btnBorrar'>Borrar</button></div></div>"  
        }],
        //Para cambiar el lenguaje a español
        "language": {
                "lengthMenu": "Mostrar _MENU_ registros",
                "zeroRecords": "No se encontraron resultados",
                "info": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "infoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sSearch": "Buscar:",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast":"Último",
                    "sNext":"Siguiente",
                    "sPrevious": "Anterior"
                },
                "sProcessing":"Procesando...",
            } 
        });

    $("#btnNuevo").click(function(){
        $("#formusuarios").trigger("reset");
        $(".modal-header").css("background-color", "#28a745");
        $(".modal-header").css("color", "white");
        $(".modal-title").text("Nuevo Usuario");            
        $("#modalCRUD").modal("show");
        
        $("#clave").html('<label for="contrasena" class="col-form-label">Contraseña:</label><input type="password" class="form-control" id="contrasena">');
        id=null;
        opcion = 1; //agregar
    });

    var fila; //capturar la fila para editar o borrar el registro

    $("#formusuarios").submit(function(e){
        e.preventDefault();
        nombre = $.trim($("#nombre").val());
        usuario = $.trim($("#usuario").val());
        contrasena = $.trim($("#contrasena").val());
        correo = $.trim($("#correo").val()); 
        telefono = $.trim($("#telefono").val()); 
        tipo = $.trim($("#tipo").val());    
        $.ajax({
            url: "nucleo/accion/usuarios",
            type: "POST",
            dataType: "json",
            data: {id:id, nombre:nombre, usuario:usuario, contrasena:contrasena, correo:correo, telefono:telefono, tipo:tipo, opcion:opcion},
            success: function(data){
                if(opcion == 1){
                    tablausuarios.row.add([id,nombre,usuario,correo,telefono,tipo]).draw();
                }else{
                    tablausuarios.row(fila).data([id,nombre,usuario,correo,telefono,tipo]).draw();
                }            
            }        
        });
        $("#modalCRUD").modal("hide");    
        
    }); 

    //botón EDITAR    
    $(document).on("click", ".btnEditar", function(){
        fila = $(this).closest("tr");
        id = parseInt(fila.find('td:eq(0)').text());
        nombre = fila.find('td:eq(1)').text();
        usuario = fila.find('td:eq(2)').text();
        correo = fila.find('td:eq(3)').text();
        telefono = fila.find('td:eq(4)').text();
        tipo = fila.find('td:eq(5)').text();
        if(tipo=='Cliente'){
            var html = '<option value="Administrador" selected>Administrador</option><option value="Cliente">Cliente</option>';
        }else{
            var html = '<option value="Administrador">Administrador</option><option value="Cliente" selected>Cliente</option>';
        }
        opcion = 2; //Editar
        
        $("#id").val(id);
        $("#nombre").val(nombre);
        $("#usuario").val(usuario);
        $("#correo").val(correo);
        $("#telefono").val(telefono);
        $("#tipo").html(html);
        $("#clave").html('');

        $(".modal-header").css("background-color", "#007bff");
        $(".modal-header").css("color", "white");
        $(".modal-title").text("Editar Usuario");            
        $("#modalCRUD").modal("show");  
        
    });

    //botón BORRAR
    $(document).on("click", ".btnBorrar", function(){    
        fila = $(this);
        id = parseInt($(this).closest("tr").find('td:eq(0)').text());
        opcion = 3 //borrar
        var respuesta = confirm("¿Está seguro de eliminar el registro: "+id+"?");
        if(respuesta){
            $.ajax({
                url: "nucleo/accion/usuarios",
                type: "POST",
                dataType: "json",
                data: {opcion:opcion, id:id},
                success: function(){
                    tablausuarios.row(fila.parents('tr')).remove().draw();
                }
            });
        }   
    });

    });
</script>

<!--Modal para CRUD-->
<div class="modal fade" id="modalCRUD" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
            </div>
        <form id="formusuarios">    
            <div class="modal-body">
                <div class="form-group">
                    <label for="nombre" class="col-form-label">Nombre:</label>
                    <input type="text" class="form-control" id="nombre" required>
                    </div>
                    <div class="form-group">
                    <label for="usuario" class="col-form-label">Usuario:</label>
                    <input type="text" class="form-control" id="usuario" required>
                    </div>
                    <div class="form-group" id="clave">
                    <label for="contrasena" class="col-form-label">Contraseña:</label>
                    <input type="password" class="form-control" id="contrasena" required>
                    </div>
                    <div class="form-group">
                    <label for="correo" class="col-form-label">Correo:</label>
                    <input type="email" class="form-control" id="correo" required>
                    </div>
                    <div class="form-group">
                    <label for="telefono" class="col-form-label">Teléfono:</label>
                    <input type="number" class="form-control" id="telefono" required>
                    </div>
                    <div class="form-group">
                    <label for="tipo" class="col-form-label">Rol del usuario:</label>
                    <select class="form-control" name="tipo" id="tipo">
                        <option value="Administrador">Administrador</option>
                        <option value="Cliente" selected>Cliente</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="id">
                <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                <button type="submit" id="btnGuardar" class="btn btn-dark">Guardar</button>
            </div>
        </form>    
        </div>
    </div>
</div> 



<!--Final del contenido principal-->

<?php include "interfaz/administrador/layouts/parte_inferior.php"?>