<!DOCTYPE HTML>

<html>
	<head>
		<title>Contáctenos | PoasadaABBAPapi</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="interfaz/usuario/assets/css/main.css" />
		<link rel="stylesheet" href="interfaz/usuario/assets/fontawesome-free/css/all.min.css" />
		<link rel="icon" href="interfaz/usuario/images/logo.ico">
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1><a href="">Posada ABBAPapi</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="">Inicio</a></li>
							<li>
								<a href="" class="icon solid fa-angle-down">Menú</a>
								<ul>
									<li><a href="generico">Acerca de</a></li>
									<li><a href="contactos">Servicios</a></li>
									<li><a href="interfaz/usuario/elements.html">Galeria</a></li>
									<li><a href="interfaz/usuario/elements.html">Contáctenos</a></li>
									<li>

									</li>
								</ul>
							</li>
							<li><a href="iniciar-sesion" class="button">Iniciar Sesión</a></li>
							<li><a href="registrar" class="button">Registrate</a></li>
						</ul>
					</nav>
				</header>

			
				<section id="main" class="container medium">
					<header>
						<h2>Contáctenos</h2>
						<p>Para disfrutar de nuestros servicios y comodidades hogareñas.</p>
					</header>
					<div class="box">
						<form method="post" action="#">
							<div class="row gtr-50 gtr-uniform">
								<div class="col-6 col-12-mobilep">
									<input type="text" name="name" id="name" value="" placeholder="Nombre y Apellido" />
								</div>
								<div class="col-6 col-12-mobilep">
									<input type="email" name="email" id="email" value="" placeholder="Correo" />
								</div>
								<div class="col-12">
									<input type="text" name="subject" id="subject" value="" placeholder="Asunto" />
								</div>
								<div class="col-12">
									<textarea name="message" id="message" placeholder="Mensaje" rows="6"></textarea>
								</div>
								<div class="col-12">
									<ul class="actions special">
										<li><input type="submit" value="Enviar Mensaje" /></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="interfaz/usuario/Construccion.html" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="interfaz/usuario/Construccion.html" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="interfaz/usuario/Construccion.html" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="interfaz/usuario/Construccion.html" class="icon brands fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; All rights reserved.</li><li>Design: <a href="interfaz/usuario/Construccion.html">Gaxxs Company</a></li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="interfaz/usuario/assets/js/jquery.min.js"></script>
			<script src="interfaz/usuario/assets/js/jquery.dropotron.min.js"></script>
			<script src="interfaz/usuario/assets/js/jquery.scrollex.min.js"></script>
			<script src="interfaz/usuario/assets/js/browser.min.js"></script>
			<script src="interfaz/usuario/assets/js/breakpoints.min.js"></script>
			<script src="interfaz/usuario/assets/js/util.js"></script>
			<script src="interfaz/usuario/assets/js/main.js"></script>

	</body>
</html>