<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Acerca de | Posada ABBAPapi</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="interfaz/usuario/assets/css/main.css" />
		<link rel="stylesheet" href="interfaz/usuario/assets/fontawesome-free/css/all.min.css" />
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1><a href="">Posada ABBAPapi</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="">Inicio</a></li>
							<li>
								<a href="" class="icon solid fa-angle-down">Menú</a>
								<ul>
									<li><a href="generico">Acerca de</a></li>
									<li><a href="#">Servicios</a></li>
									<li><a href="#">Galeria</a></li>
									<li><a href="contactos">Contactenos</a></li>
								</ul>
							</li>
							<li><a href="iniciar-sesion" class="button">Iniciar Sesión</a></li>
							<li><a href="registrar" class="button">Registrate</a></li>
							
							
						</ul>
					</nav>
				</header>

			<!-- Main -->
				<section id="main" class="container">
					<header>
						<h2>Generic</h2>
						<p>A generic page for every non-generic situation.</p>
					</header>
					<div class="box">
						<span class="image featured"><img src="images/pic01.jpg" alt="" /></span>
						<h3>This is a subheading</h3>
						<p>Cep risus aliquam gravida cep ut lacus amet. Adipiscing faucibus nunc placerat. Tempus adipiscing turpis non blandit accumsan eget lacinia nunc integer interdum amet aliquam ut orci non col ut ut praesent. Semper amet interdum mi. Phasellus enim laoreet ac ac commodo faucibus faucibus. Curae ante vestibulum ante. Blandit. Ante accumsan nisi eu placerat gravida placerat adipiscing in risus fusce vitae ac mi accumsan nunc in accumsan tempor blandit aliquet aliquet lobortis. Ultricies blandit lobortis praesent turpis. Adipiscing accumsan adipiscing adipiscing ac lacinia cep. Orci blandit a iaculis adipiscing ac. Vivamus ornare laoreet odio vis praesent nunc lorem mi. Erat. Tempus sem faucibus ac id. Vis in blandit. Nascetur ultricies blandit ac. Arcu aliquam. Accumsan mi eget adipiscing nulla. Non vestibulum ac interdum condimentum semper commodo massa arcu.</p>
						<div class="row">
							<div class="row-6 row-12-mobilep">
								<h3>And now a subheading</h3>
								<p>Adipiscing faucibus nunc placerat. Tempus adipiscing turpis non blandit accumsan eget lacinia nunc integer interdum amet aliquam ut orci non col ut ut praesent. Semper amet interdum mi. Phasellus enim laoreet ac ac commodo faucibus faucibus. Curae lorem ipsum adipiscing ac. Vivamus ornare laoreet odio vis praesent.</p>
							</div>
							<div class="row-6 row-12-mobilep">
								<h3>And another subheading</h3>
								<p>Adipiscing faucibus nunc placerat. Tempus adipiscing turpis non blandit accumsan eget lacinia nunc integer interdum amet aliquam ut orci non col ut ut praesent. Semper amet interdum mi. Phasellus enim laoreet ac ac commodo faucibus faucibus. Curae lorem ipsum adipiscing ac. Vivamus ornare laoreet odio vis praesent.</p>
							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; All rights reserved.</li><li>Design: <a href="interfaz/usuario/Construccion.php">Gaxxs Company</a></li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="interfaz/usuario/assets/js/jquery.min.js"></script>
			<script src="interfaz/usuario/assets/js/jquery.dropotron.min.js"></script>
			<script src="interfaz/usuario/assets/js/jquery.scrollex.min.js"></script>
			<script src="interfaz/usuario/assets/js/browser.min.js"></script>
			<script src="interfaz/usuario/assets/js/breakpoints.min.js"></script>
			<script src="interfaz/usuario/assets/js/util.js"></script>
			<script src="interfaz/usuario/assets/js/main.js"></script>

	</body>
</html>