<!DOCTYPE HTML>

<html lang="es">
		<!-- Conexiones-->
	<head>
		<title>Posada ABBAPapi</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="interfaz/usuario/assets/css/main.css"/>
		<link rel="stylesheet" href="interfaz/usuario/assets/fontawesome-free/css/all.min.css" />
		<link rel="icon" href="interfaz/usuario/images/logo.ico">
	</head>
	


	<body class="landing is-preload">
		<div id="page-wrapper">

			<!-- Emcabezamiento -->
				<header id="header" class="alt">
					<h1><a href="">Posada ABBAPapi</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="#banner">Inicio</a></li>
							<li>
								<a href="" class="icon solid fa-angle-down" >Menú</a>
								<ul>
									<li><a href="#servicios">Servicios</a></li>
									<li><a href="#galeria">Galeria</a></li>
									<li><a href="#footer">Contactenos</a></li>

									
								</ul>
							</li>
							<li><a href="registrar" class="button">Registrate</a></li>
							
							
						</ul>
					</nav>
				</header>

			<!-- Bandera -->
				<section id="banner">
					<h2>Posada ABBAPapi</h2>
					<p>Abre la puerta a un mundo nuevo</p>
					<ul class="actions special">
						<li><a href="iniciar-sesion" class="button">Iniciar Sesión</a></li>
						
						
					</ul>
				</section>

			<!-- Principal -->
				<section id="main" class="container">

					<section class="box special">
						<header class="major">
							<h2>Experimenta una buena estadía y disfruta de fantasticas ofertas.</h2>
							<p>Disfruta del estilo hogareño y siente la verdadera comodidad.</p>
						</header>
						<span><img src="images/pic01.jpg" alt="" /></span>
					</section>

					

					<section class="box special features" id="servicios">

					<h2>Nuestros servicios</h2>
					<br>
						<div class="features-row">
							<section>
								<span class="icon solid major fa-bolt accent2"></span>
								<h3>Cobertura wifi</h3>
								<p>Experimenta una conexión estable y rápida de internet mientras disfrutas de la comodidad de tu estadía.</p>
							</section>


							<section>
								<span class="icon solid major fa-chart-area accent3"></span>
								<h3>Habitaciones principales</h3>
								<p>Ofrecemos habitaciones principales para que puedas disfutar en solitario o en familia.</p>
							</section>


						</div>
						<div class="features-row">
							
							<section>
								<span class="icon solid major fa-cloud accent4"></span>
								<h3>Balcón con vista al paisaje</h3>
								<p>Disfuta del atardecer y amanecer mientras experimentas la comodidad hogareña. </p>
							</section>
							
							<section>
								<span class="icon solid major fa-lock accent5"></span>
								<h3>Seguridad las 24 horas</h3>
								<p>Ofrecemos la mejor seguridad las 24 horas para que puedas relajarte en las noches sin preocupaciones.</p>
							</section>
						</div>
					</section>

					<h2 style="text-align: center;" id="galeria">Galeria de imagenes</h2>
					<section class= "galeria">
							

						<a href="#image1">
							<img src="interfaz\usuario\images/g1.jpg" alt="">
						</a>
						<a href="#image2">
							<img src="interfaz\usuario\images/g2.jpg" alt="">
						</a>
						<a href="#image3">
							<img src="interfaz\usuario\images/g3.jpg" alt="">
						</a>
						<a href="#image4">
							<img src="interfaz\usuario\images/g6.jpg" alt="">
						</a>
						<a href="#image5">
							<img src="interfaz\usuario\images/g7.jpg" alt="">
						</a>
						<a href="#image6">
							<img src="interfaz\usuario\images/g8.jpg" alt="">
						</a>
						<a href="#image7">
							<img src="interfaz\usuario\images/g9.jpg" alt="">
						</a>
						<a href="#image8">
							<img src="interfaz\usuario\images/g10.jpg" alt="">
						</a>
							
					</section>
						<article class="light-box" id="image1">
							<a href="#image8" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g1.jpg" alt="">
							<a href="#image2" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image2">
							<a href="#image1" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g2.jpg" alt="">
							<a href="#image3" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image3">
							<a href="#image2" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g3.jpg" alt="">
							<a href="#image4" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image4">
							<a href="#image3" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g6.jpg" alt="">
							<a href="#image5" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image5">
							<a href="#image4" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g7.jpg" alt="">
							<a href="#image6" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image6">
							<a href="#image5" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g8.jpg" alt="">
							<a href="#image7" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image7">
							<a href="#image6" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g9.jpg" alt="">
							<a href="#image8" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>

						<article class="light-box" id="image8">
							<a href="#image7" class="next"><i class="fas fa-arrow-left"></i></a>
							<img src="interfaz\usuario\images/g10.jpg" alt="">
							<a href="#image1" class="next"><i class="fas fa-arrow-right"></i></a>
							<a href="#" class="close">X</a>
							
						</article>
				</section>
<style>
	/*************************
	********portfolio CSS*****
	**************************/

	.galeria{
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
		width: 95%;
		margin: auto;
		grid-gap: 10px;
		padding: 40px 0;
		overflow: hidden;
	}

	.galeria > a{
		display: block;
		position: relative;
		overflow: hidden;
		box-shadow: 0 0 6px rgba(0, 0, 0, .5);
	}
	.galeria img{
		width: 100%;
		vertical-align: top;
		height: 300px;
		object-fit: cover;
		transition: transform 0.5s;
	}

	.galeria a:hover img{
		filter: blur(2px);
		transform: rotate(10deg) scale(1.3);
	}

	.light-box{
		position: fixed;
		top: 0;
		left: 0;
		background: rgba(0, 0, 0, .5);
		transition: transform .3s ease-in-out;
		width: 100%;
		height: 100vh;
		z-index: 1000;
		display: flex;
		justify-content: center;
		align-items: center;
		transform: scale(0);
	}
	.light-box img{
		width: 75vw;
		max-height: 70vh;
	}

	.light-box:target{
		transform: scale(1);
	}
	.close{
		display: block;
		position: absolute;
		top: 60px;
		right: 40px;
		background:#851919;
		color: #fff;
		text-decoration: none;
		width: 40px;
		height: 40px;
		text-align: center;
		line-height: 40px;
		border-radius: 40%;
	}

	.next{
		display: block;
		background: #851919;
		color: #fff;
		height: 30px;
		width: 30px;
		line-height: 30px;
		text-decoration: none;
		text-align: center;
	}

	@media screen and (max-whidth:400px){
		.galeria{
			grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
		}
		.close{
			top: 20px;
			right: 20px;
		}
	}
</style>			

			<!-- Footer -->
			<footer id="footer">  
				<!--<h2 style="font-size: 30px; margin-top: -50px; margin-bottom: 30px;">Contactenos</h2> 
				
				<address style="font-size: 16px; text-align: left; margin-left: 4px;">
                                    <ul>
                                        <span> <i class="icono fas fa-clock"></i> Dirección:</span>
                                        <p>Casanay</p>
                                    </ul>
                                    
                                    <ul>
                                        <span> <i class="icono fas fa-clock"></i> Horario de trabajo:</span>
                                        <p>Lunes  - Viernes de 9am a 5pm</p>
                                    </ul>
                                    
									<ul>
                                        <span ><i class="icono fas fa-envelope"></i> Correo:</span>
                                        <p>gabrielgallardo246@gmail.com</p>
                                    </ul> 
                                    <ul>
                                    	<span> <i class="icono fas fa-phone-alt"></i> Teléfono:</span>
                                        <p>0424-817-00-76</p>
                                    </ul>
									
									
                                </address> -->

				
				
					<ul class="icons">
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="interfaz/usuario/Construccion.php" class="icon brands fa-google-plus"><span class="label">Google+</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; All rights reserved.</li><li>Design: <a href="#">Gaxxs Company</a></li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="interfaz/usuario/assets/js/jquery.min.js"></script>
			<script src="interfaz/usuario/assets/js/jquery.dropotron.min.js"></script>
			<script src="interfaz/usuario/assets/js/jquery.scrollex.min.js"></script>
			<script src="interfaz/usuario/assets/js/browser.min.js"></script>
			<script src="interfaz/usuario/assets/js/breakpoints.min.js"></script>
			<script src="interfaz/usuario/assets/js/util.js"></script>
			<script src="interfaz/usuario/assets/js/main.js"></script>

	</body>
</html>