<!DOCTYPE HTML>
<html lang="es">
	<?php include "interfaz/usuario/layouts/parte_superior.php"?>
    <link rel="stylesheet" href="interfaz/administrador/css/perfil.css">
	<body class="landing is-preload">
		<div id="page-wrapper">
			<?php include "interfaz/usuario/layouts/header.php"?>
			<!-- Principal -->
				<section id="main" class="container">
                    <section class="seccion-perfil-usuario" style="margin-top: -70px;">
                        <div class="perfil-usuario-header">
                            <div class="perfil-usuario-portada">
                                <div class="perfil-usuario-avatar">
                                    <img  src="./interfaz/administrador/img/undraw_profile.svg">  
                                </div>   
                            </div>
                        </div>

                            <div class="perfil-usuario-body">
                                <a href="configuracion" style="position:absolute; top: 40px; right: 10px;"><i class="fas fa-edit"></i>Editar perfil</a>
                                <div class="perfil-usuario-bio">
                                    <h3 class="titulo"><?php echo $_SESSION['usuario']['nombre'];?></h3>
                                </div>
                                
                                <div class="perfil-usuario-footer">
                                    <ul class="lista-datos">
                                        <li><i class="icono fas fa-map-signs"></i> ID: <?php echo $_SESSION['usuario']['id'];?></li>
                                        <li><i class="icono fas fa-user-check"></i> Usuario: <?php echo $_SESSION['usuario']['usuario'];?></li>
                                        <li><i class="icono fas fa-building"></i> Nivel de usuario: <?php echo $_SESSION['usuario']['tipo'];?></li>
                                        
                                    </ul>
                                    <ul class="lista-datos">
                                    <li><i class="icono fas fa-envelope"></i> Correo: <?php echo $_SESSION['usuario']['correo'];?></li>
                                    <li><i class="icono fas fa-phone-alt"></i> Telefono: <?php echo $_SESSION['usuario']['telefono'];?></li>
                                    </ul>
                                </div>
                            </div>
                            <br>
                            <br>
                    </section>
				</section>
			<?php include "interfaz/usuario/layouts/footer.php"?>
		</div>
		<?php include "interfaz/usuario/layouts/parte_inferior.php"?>
	</body>
</html>